version: '3.8'

services:
  telegram-bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - YCLIENTS_PARTNER_TOKEN=${YCLIENTS_PARTNER_TOKEN}
      - YCLIENTS_USER_TOKEN=${YCLIENTS_USER_TOKEN}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
